-----------------------------------
-- func: nmhuntone list 150 tier 1-3
-- desc: prints out list of kill counts
-----------------------------------
local commandObj = {}

commandObj.cmdprops =
{
    permission = 0,
    parameters = 'is'
}

local function error(player, msg)
    player:printToPlayer(msg)
    player:printToPlayer('!nmhuntone <tier>')
end

commandObj.onTrigger = function(player, amount)

    if amount == nil or amount < 1 then
        error(player, 'Invalid tier, please enter 1 - 3.')
        return
    end

local aa = player:getCharVar('[NMHunt]DE_Alea')
local ab = player:getCharVar('[NMHunt]DE_Angun')
local ac = player:getCharVar('[NMHunt]DE_Aura')
local ad = player:getCharVar('[NMHunt]DE_Azryat')
local ae = player:getCharVar('[NMHunt]DE_Blissia')
local af = player:getCharVar('[NMHunt]DE_Braka')
local ag = player:getCharVar('[NMHunt]DE_Bulruk')
local ah = player:getCharVar('[NMHunt]DE_Chemraul')
local ai = player:getCharVar('[NMHunt]DE_Cosmic')
local aj = player:getCharVar('[NMHunt]DE_Dagurt')
local ak = player:getCharVar('[NMHunt]DE_Dermetris')
local al = player:getCharVar('[NMHunt]DE_Dorath')
local am = player:getCharVar('[NMHunt]DE_Duvrion')
local an = player:getCharVar('[NMHunt]DE_Elda')
local ao = player:getCharVar('[NMHunt]DE_Eroan')
local ap = player:getCharVar('[NMHunt]DE_Faelar')
local aq = player:getCharVar('[NMHunt]DE_Foxfire')
local ar = player:getCharVar('[NMHunt]DE_Gallious')
local as = player:getCharVar('[NMHunt]DE_Gogu')
local at = player:getCharVar('[NMHunt]DE_Gylledha')
local au = player:getCharVar('[NMHunt]DE_Horar')
local av = player:getCharVar('[NMHunt]DE_Ingivald')
local aw = player:getCharVar('[NMHunt]DE_Jassin')
local ax = player:getCharVar('[NMHunt]DE_Josidiah')
local ay = player:getCharVar('[NMHunt]DE_Klayden')
local az = player:getCharVar('[NMHunt]DE_Kystal')
local ba = player:getCharVar('[NMHunt]DE_Lipith')
local bb = player:getCharVar('[NMHunt]DE_Majesty')
local bc = player:getCharVar('[NMHunt]DE_Milky Way')
local bd = player:getCharVar('[NMHunt]DE_Morthil')
local be = player:getCharVar('[NMHunt]DE_Narbeth')
local bf = player:getCharVar('[NMHunt]DE_Nightshade')
local bg = player:getCharVar('[NMHunt]DE_Nym')
local bh = player:getCharVar('[NMHunt]DE_Ophelia')
local bi = player:getCharVar('[NMHunt]DE_Pharom')
local bj = player:getCharVar('[NMHunt]DE_Pyrder')
local bk = player:getCharVar('[NMHunt]DE_Rammir')
local bl = player:getCharVar('[NMHunt]DE_Rijjat')
local bm = player:getCharVar('[NMHunt]DE_Salvor')
local bn = player:getCharVar('[NMHunt]DE_Séverin')
local bo = player:getCharVar('[NMHunt]DE_Silvyr')
local bp = player:getCharVar('[NMHunt]DE_Soldelle')
local bq = player:getCharVar('[NMHunt]DE_Sterling')
local br = player:getCharVar('[NMHunt]DE_Syfyn')
local bs = player:getCharVar('[NMHunt]DE_Thalia')
local bt = player:getCharVar('[NMHunt]DE_Toki')
local bu = player:getCharVar('[NMHunt]DE_Uldreiyn')
local bv = player:getCharVar('[NMHunt]DE_Vayzen')
local bw = player:getCharVar('[NMHunt]DE_Voggur')
local bx = player:getCharVar('[NMHunt]DE_Wistari')
local by = player:getCharVar('[NMHunt]DE_Aleera')
local bz = player:getCharVar('[NMHunt]DE_Anya')
local ca = player:getCharVar('[NMHunt]DE_Auris')
local cb = player:getCharVar('[NMHunt]DE_Azura')
local cc = player:getCharVar('[NMHunt]DE_Blossom')
local cd = player:getCharVar('[NMHunt]DE_Breya')
local ce = player:getCharVar('[NMHunt]DE_Caelia')
local cf = player:getCharVar('[NMHunt]DE_Ciradyl')
local cg = player:getCharVar('[NMHunt]DE_Crystal')
local ch = player:getCharVar('[NMHunt]DE_Darcassan')
local ci = player:getCharVar('[NMHunt]DE_Devella')
local cj = player:getCharVar('[NMHunt]DE_Doreah')
local ck = player:getCharVar('[NMHunt]DE_Dynastra')
local cl = player:getCharVar('[NMHunt]DE_Eldar')
local cm = player:getCharVar('[NMHunt]DE_Erthel')
local cn = player:getCharVar('[NMHunt]DE_Faelyn')
local co = player:getCharVar('[NMHunt]DE_Freya')
local cp = player:getCharVar('[NMHunt]DE_Gandor')
local cq = player:getCharVar('[NMHunt]DE_Gold Horn')
local cr = player:getCharVar('[NMHunt]DE_Hadena')
local cs = player:getCharVar('[NMHunt]DE_Hungus')
local ct = player:getCharVar('[NMHunt]DE_Ioguss')
local cu = player:getCharVar('[NMHunt]DE_Jayldrog')
local cv = player:getCharVar('[NMHunt]DE_Kalodor')
local cw = player:getCharVar('[NMHunt]DE_Kolzreid')
local cx = player:getCharVar('[NMHunt]DE_Lago')
local cy = player:getCharVar('[NMHunt]DE_Lofar')
local cz = player:getCharVar('[NMHunt]DE_Malfas')
local da = player:getCharVar('[NMHunt]DE_Minelle')
local db = player:getCharVar('[NMHunt]DE_Mortusra')
local dc = player:getCharVar('[NMHunt]DE_Narvari')
local dd = player:getCharVar('[NMHunt]DE_Nightwind')
local de = player:getCharVar('[NMHunt]DE_Nyssa')
local df = player:getCharVar('[NMHunt]DE_Oribel')
local dg = player:getCharVar('[NMHunt]DE_Phyrra')
local dh = player:getCharVar('[NMHunt]DE_Quamara')
local di = player:getCharVar('[NMHunt]DE_Randil')
local dj = player:getCharVar('[NMHunt]DE_Rorik')
local dk = player:getCharVar('[NMHunt]DE_Sanguisus')
local dl = player:getCharVar('[NMHunt]DE_Shadoras')
local dm = player:getCharVar('[NMHunt]DE_Sirius')
local dn = player:getCharVar('[NMHunt]DE_Solstice')
local doo = player:getCharVar('[NMHunt]DE_Sudryl')
local dp = player:getCharVar('[NMHunt]DE_Taena')
local dq = player:getCharVar('[NMHunt]DE_Thingol')
local dr = player:getCharVar('[NMHunt]DE_Turgon')
local ds = player:getCharVar('[NMHunt]DE_Usha')
local dt = player:getCharVar('[NMHunt]DE_Vesryn')
local du = player:getCharVar('[NMHunt]DE_Vyn')
local dv = player:getCharVar('[NMHunt]DE_Withil')
local dw = player:getCharVar('[NMHunt]DE_Alva')
local dx = player:getCharVar('[NMHunt]DE_Aqrilla')
local dy = player:getCharVar('[NMHunt]DE_Austi')
local dz = player:getCharVar('[NMHunt]DE_Balrus')
local ea = player:getCharVar('[NMHunt]DE_Bonesnapper')
local eb = player:getCharVar('[NMHunt]DE_Brilbelle')
local ec = player:getCharVar('[NMHunt]DE_Caldor')
local ed = player:getCharVar('[NMHunt]DE_Ciscra')
local ee = player:getCharVar('[NMHunt]DE_Daealla')
local ef = player:getCharVar('[NMHunt]DE_Darfin')
local eg = player:getCharVar('[NMHunt]DE_Dezaral')
local eh = player:getCharVar('[NMHunt]DE_Drachenstein')
local ei = player:getCharVar('[NMHunt]DE_Earthtaker')
local ej = player:getCharVar('[NMHunt]DE_Electra')
local ek = player:getCharVar('[NMHunt]DE_Esmeralla')
local el = player:getCharVar('[NMHunt]DE_Farkas')
local em = player:getCharVar('[NMHunt]DE_Frostar')
local en = player:getCharVar('[NMHunt]DE_Gaylia')
local eo = player:getCharVar('[NMHunt]DE_Golden Moon')
local ep = player:getCharVar('[NMHunt]DE_Haela')
local eq = player:getCharVar('[NMHunt]DE_Igninitis')
local er = player:getCharVar('[NMHunt]DE_Ismzal')
local es = player:getCharVar('[NMHunt]DE_Jewel')
local et = player:getCharVar('[NMHunt]DE_Kalseru')
local eu = player:getCharVar('[NMHunt]DE_Kuskyn')
local ev = player:getCharVar('[NMHunt]DE_Laimus')
local ew = player:getCharVar('[NMHunt]DE_Luna')
local ex = player:getCharVar('[NMHunt]DE_Malok')
local ey = player:getCharVar('[NMHunt]DE_Mireille')
local ez = player:getCharVar('[NMHunt]DE_Myrinn')
local fa = player:getCharVar('[NMHunt]DE_Neldor')
local fb = player:getCharVar('[NMHunt]DE_Nightwing')
local fc = player:getCharVar('[NMHunt]DE_Oddfinnur')
local fd = player:getCharVar('[NMHunt]DE_Orion')
local fe = player:getCharVar('[NMHunt]DE_Pindious')
local ff = player:getCharVar('[NMHunt]DE_Quintus')
local fg = player:getCharVar('[NMHunt]DE_Remus')
local fh = player:getCharVar('[NMHunt]DE_Rotnam')
local fi = player:getCharVar('[NMHunt]DE_Saphil')
local fj = player:getCharVar('[NMHunt]DE_Sheedra')
local fk = player:getCharVar('[NMHunt]DE_Skeltos')
local fl = player:getCharVar('[NMHunt]DE_Soril')
local fm = player:getCharVar('[NMHunt]DE_Sulfu')
local fn = player:getCharVar('[NMHunt]DE_Talila')
local fo = player:getCharVar('[NMHunt]DE_Throar')
local fp = player:getCharVar('[NMHunt]DE_Turilla')
local fq = player:getCharVar('[NMHunt]DE_Usunaar')
local fr = player:getCharVar('[NMHunt]DE_Viktas')
local fs = player:getCharVar('[NMHunt]DE_Wilda')
local ft = player:getCharVar('[NMHunt]DE_Wynstar')

if amount == 1 then 

player:printToPlayer(string.format('-------------------------------------------------------------------------------------------'), xi.msg.channel.SYSTEM_3)

player:printToPlayer(string.format('NM Hunt Kill Count Tier 1--Current Kills are %s of 50--------------------------------------',player:getCharVar('[NMHunt]TOneKills')), xi.msg.channel.SYSTEM_3)

player:printToPlayer(string.format('-------------------------------------------------------------------------------------------'),  xi.msg.channel.SYSTEM_3)
player:printToPlayer(string.format('Ailmar %s | Amara %s | Aquarun %s | Axil %s | Bellas %s | ',aa,ab,ac,ad,ae), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Bonna %s | Brina %s | Celestia %s | Cluym %s | Daemeon %s | ',af,ag,ah,ai,aj), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Dark Rain %s | Diamond %s | Dracyian %s | Edmyla %s | Elora %s | ',ak,al,am,an,ao), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Estelar %s | Finrod %s | Fundar %s | Gelda %s | Golvig %s | ',ap,aq,ar,as,at), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Haemir %s | Igor %s | Ithi %s | Jhaan %s | Keara %s | ',au,av,aw,ax,ay), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Kyla %s | Lavatius %s | Lunarex %s | Malumka %s | Misi %s | ',az,ba,bb,bc,bd), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Mysris %s | Nemredilth %s | Nindr  %s | Olwyn %s | Orym  %s | ',be,bf,bg,bh,bi), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Pondra %s | Ragna %s | Rennyn %s | Sabir  %s | Sapphire %s | ',bj,bk,bl,bm,bn), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Shikta %s | Slyvek %s | Star Light %s | Sunshine %s | Tanulia %s | ',bo,bp,bq,br,bs), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Tisnip %s | Turvass %s | Vaegon  %s | Vinelle %s | Wilkass %s | ',bt,bu,bv,bw,bx), 3, xi.msg.channel.system_3)

elseif amount == 2 then 

player:printToPlayer(string.format('-------------------------------------------------------------------------------------------'), xi.msg.channel.SYSTEM_3)

player:printToPlayer(string.format('NM Hunt Kill Count Tier 2--Current Kills are %s of 50--------------------------------------',player:getCharVar('[NMHunt]TTwoKills')), xi.msg.channel.SYSTEM_3)

player:printToPlayer(string.format('-------------------------------------------------------------------------------------------'),  xi.msg.channel.SYSTEM_3)
player:printToPlayer(string.format('Akibrus %s | Amerstal %s | Asralyn %s | Ayldrad %s | Bellesta %s | ',by,bz,ca,cb,cc), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Bonnwynn %s | Brobek %s | Chalia %s | Coalak %s | Daernip %s | ',cd,ce,cf,cg,ch), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Darvyn %s | Digroi %s | Dray %s | Eiki %s | Elwin %s | ',ci,cj,ck,cl,cm), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Fabien %s | Flammedra %s | Gaemon %s | Gembelle %s | Gremin %s | ',cn,co,cp,cq,cr), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Hastos %s | Ilbryn %s | Jaderyn %s | Jinvia %s | Kezda %s | ',cs,ct,cu,cv,cw), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Kymil %s | Lavinia %s | Lymseia  %s | Merlara %s | Misma %s | ',cx,cy,cz,da,db), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Mystique %s | Nesterin  %s | Noi %s | Onas  %s | Pearl Moon %s | ',dc,dd,de,df,dg), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Pondral %s | Ragriel %s | Reyda %s | Saeya %s | Sarielle %s | ',dh,di,dj,dk,dl), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Shirmyl %s | Snowflake %s | Starburst %s | Sybella %s | Tazlen %s | ',dm,dn,doo,dp,dq), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Tisthel %s | Twilight %s | Vaella %s | Virfi %s | Wiska %s | ',dr,ds,dt,du,dv), 3, xi.msg.channel.system_3)

elseif amount == 3 then 

player:printToPlayer(string.format('-------------------------------------------------------------------------------------------'), xi.msg.channel.SYSTEM_3)

player:printToPlayer(string.format('NM Hunt Kill Count Tier 3--Current Kills are %s of 50--------------------------------------',player:getCharVar('[NMHunt]TThreeKills')), xi.msg.channel.SYSTEM_3)

player:printToPlayer(string.format('-------------------------------------------------------------------------------------------'),  xi.msg.channel.SYSTEM_3)
player:printToPlayer(string.format('Akkar %s | Angor %s | Astra %s | Azariah %s | Belstram %s | ',dw,dx,dy,dz,ea), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Bragi %s | Brulin %s | Chandrelle %s | Corym %s | Dagen %s | ',eb,ec,ed,ee,ef), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Delvin %s | Dimlinn %s | Drusila %s | Eilivur %s | Engar %s | ',eg,eh,ei,ej,ek), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Fada %s | Floki %s | Galdor %s | Glacitus %s | Gusak %s | ',el,em,en,eo,ep), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Heptin %s | Ilyrana %s | Jai-Blynn %s | Jodis %s | Killin %s | ',eq,er,es,et,eu), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Kyra %s | Lija %s | Lyra %s | Midnight %s | Mistmael %s | ',ev,ew,ex,ey,ez), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Nalra %s | Night Moon %s | Norok %s | Onnyx %s | Peregrine %s | ',fa,fb,fc,fd,fe), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Prodos %s | Rainbow %s | Rhenalyrr %s | Sakakara %s | Serpretus %s | ',ff,fg,fh,fi,fj), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Silver Star %s | Sola %s | Stardust %s | Syfas %s | Tendris %s | ',fk,fl,fm,fn,fo), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Tiznys %s | Twinkle %s | Vasha %s | Vixen %s | Wispmaral %s | ',fp,fq,fr,fs,ft), 3, xi.msg.channel.system_3)

end
end

return commandObj
