-----------------------------------
-- func: nmhuntone list 150 tier 1-3
-- desc: prints out list of kill counts
-----------------------------------
local commandObj = {}

commandObj.cmdprops =
{
    permission = 0,
    parameters = 'is'
}

local function error(player, msg)
    player:printToPlayer(msg)
    player:printToPlayer('!nmhuntone <tier>')
end

commandObj.onTrigger = function(player, amount)

    if amount == nil or amount < 1 then
        error(player, 'Invalid tier, please enter 1 - 3.')
        return
    end

local fu = player:getCharVar('[NMHunt]DE_Alea')
local fv = player:getCharVar('[NMHunt]DE_Angun')
local fw = player:getCharVar('[NMHunt]DE_Aura')
local fx = player:getCharVar('[NMHunt]DE_Azryat')
local fy = player:getCharVar('[NMHunt]DE_Blissia')
local fz = player:getCharVar('[NMHunt]DE_Braka')
local ga = player:getCharVar('[NMHunt]DE_Bulruk')
local gb = player:getCharVar('[NMHunt]DE_Chemraul')
local gc = player:getCharVar('[NMHunt]DE_Cosmic')
local gd = player:getCharVar('[NMHunt]DE_Dagurt')
local ge = player:getCharVar('[NMHunt]DE_Dermetris')
local gf = player:getCharVar('[NMHunt]DE_Dorath')
local gg = player:getCharVar('[NMHunt]DE_Duvrion')
local gh = player:getCharVar('[NMHunt]DE_Elda')
local gi = player:getCharVar('[NMHunt]DE_Eroan')
local gj = player:getCharVar('[NMHunt]DE_Faelar')
local gk = player:getCharVar('[NMHunt]DE_Foxfire')
local gl = player:getCharVar('[NMHunt]DE_Gallious')
local gm = player:getCharVar('[NMHunt]DE_Gogu')
local gn = player:getCharVar('[NMHunt]DE_Gylledha')
local go = player:getCharVar('[NMHunt]DE_Horar')
local gp = player:getCharVar('[NMHunt]DE_Ingivald')
local gq = player:getCharVar('[NMHunt]DE_Jassin')
local gr = player:getCharVar('[NMHunt]DE_Josidiah')
local gs = player:getCharVar('[NMHunt]DE_Klayden')
local gt = player:getCharVar('[NMHunt]DE_Kystal')
local gu = player:getCharVar('[NMHunt]DE_Lipith')
local gv = player:getCharVar('[NMHunt]DE_Majesty')
local gw = player:getCharVar('[NMHunt]DE_Milky Way')
local gx = player:getCharVar('[NMHunt]DE_Morthil')
local gy = player:getCharVar('[NMHunt]DE_Narbeth')
local gz = player:getCharVar('[NMHunt]DE_Nightshade')
local ha = player:getCharVar('[NMHunt]DE_Nym')
local hb = player:getCharVar('[NMHunt]DE_Ophelia')
local hc = player:getCharVar('[NMHunt]DE_Pharom')
local hd = player:getCharVar('[NMHunt]DE_Pyrder')
local he = player:getCharVar('[NMHunt]DE_Rammir')
local hf = player:getCharVar('[NMHunt]DE_Rijjat')
local hg = player:getCharVar('[NMHunt]DE_Salvor')
local hh = player:getCharVar('[NMHunt]DE_Séverin')
local hi = player:getCharVar('[NMHunt]DE_Silvyr')
local hj = player:getCharVar('[NMHunt]DE_Soldelle')
local hk = player:getCharVar('[NMHunt]DE_Sterling')
local hl = player:getCharVar('[NMHunt]DE_Syfyn')
local hm = player:getCharVar('[NMHunt]DE_Thalia')
local hn = player:getCharVar('[NMHunt]DE_Toki')
local ho = player:getCharVar('[NMHunt]DE_Uldreiyn')
local hp = player:getCharVar('[NMHunt]DE_Vayzen')
local hq = player:getCharVar('[NMHunt]DE_Voggur')
local hr = player:getCharVar('[NMHunt]DE_Wistari')
local hs = player:getCharVar('[NMHunt]DE_Aleera')
local ht = player:getCharVar('[NMHunt]DE_Anya')
local hu = player:getCharVar('[NMHunt]DE_Auris')
local hv = player:getCharVar('[NMHunt]DE_Azura')
local hw = player:getCharVar('[NMHunt]DE_Blossom')
local hx = player:getCharVar('[NMHunt]DE_Breya')
local hy = player:getCharVar('[NMHunt]DE_Caelia')
local hz = player:getCharVar('[NMHunt]DE_Ciradyl')
local ia = player:getCharVar('[NMHunt]DE_Crystal')
local ib = player:getCharVar('[NMHunt]DE_Darcassan')
local ic = player:getCharVar('[NMHunt]DE_Devella')
local id = player:getCharVar('[NMHunt]DE_Doreah')
local ie = player:getCharVar('[NMHunt]DE_Dynastra')
local lp = player:getCharVar('[NMHunt]DE_Eldar')
local ig = player:getCharVar('[NMHunt]DE_Erthel')
local ih = player:getCharVar('[NMHunt]DE_Faelyn')
local ii = player:getCharVar('[NMHunt]DE_Freya')
local ij = player:getCharVar('[NMHunt]DE_Gandor')
local ik = player:getCharVar('[NMHunt]DE_Gold Horn')
local il = player:getCharVar('[NMHunt]DE_Hadena')
local im = player:getCharVar('[NMHunt]DE_Hungus')
local lq = player:getCharVar('[NMHunt]DE_Ioguss')
local io = player:getCharVar('[NMHunt]DE_Jayldrog')
local ip = player:getCharVar('[NMHunt]DE_Kalodor')
local iq = player:getCharVar('[NMHunt]DE_Kolzreid')
local ir = player:getCharVar('[NMHunt]DE_Lago')
local is = player:getCharVar('[NMHunt]DE_Lofar')
local it = player:getCharVar('[NMHunt]DE_Malfas')
local iu = player:getCharVar('[NMHunt]DE_Minelle')
local iv = player:getCharVar('[NMHunt]DE_Mortusra')
local iw = player:getCharVar('[NMHunt]DE_Narvari')
local ix = player:getCharVar('[NMHunt]DE_Nightwind')
local iy = player:getCharVar('[NMHunt]DE_Nyssa')
local iz = player:getCharVar('[NMHunt]DE_Oribel')
local ja = player:getCharVar('[NMHunt]DE_Phyrra')
local jb = player:getCharVar('[NMHunt]DE_Quamara')
local jc = player:getCharVar('[NMHunt]DE_Randil')
local jd = player:getCharVar('[NMHunt]DE_Rorik')
local je = player:getCharVar('[NMHunt]DE_Sanguisus')
local jf = player:getCharVar('[NMHunt]DE_Shadoras')
local jg = player:getCharVar('[NMHunt]DE_Sirius')
local jh = player:getCharVar('[NMHunt]DE_Solstice')
local ji = player:getCharVar('[NMHunt]DE_Sudryl')
local jj = player:getCharVar('[NMHunt]DE_Taena')
local jk = player:getCharVar('[NMHunt]DE_Thingol')
local jl = player:getCharVar('[NMHunt]DE_Turgon')
local jm = player:getCharVar('[NMHunt]DE_Usha')
local jn = player:getCharVar('[NMHunt]DE_Vesryn')
local jo = player:getCharVar('[NMHunt]DE_Vyn')
local jp = player:getCharVar('[NMHunt]DE_Withil')
local jq = player:getCharVar('[NMHunt]DE_Alva')
local jr = player:getCharVar('[NMHunt]DE_Aqrilla')
local js = player:getCharVar('[NMHunt]DE_Austi')
local jt = player:getCharVar('[NMHunt]DE_Balrus')
local ju = player:getCharVar('[NMHunt]DE_Bonesnapper')
local jv = player:getCharVar('[NMHunt]DE_Brilbelle')
local jw = player:getCharVar('[NMHunt]DE_Caldor')
local jx = player:getCharVar('[NMHunt]DE_Ciscra')
local jy = player:getCharVar('[NMHunt]DE_Daealla')
local jz = player:getCharVar('[NMHunt]DE_Darfin')
local ka = player:getCharVar('[NMHunt]DE_Dezaral')
local kb = player:getCharVar('[NMHunt]DE_Drachenstein')
local kc = player:getCharVar('[NMHunt]DE_Earthtaker')
local kd = player:getCharVar('[NMHunt]DE_Electra')
local ke = player:getCharVar('[NMHunt]DE_Esmeralla')
local kf = player:getCharVar('[NMHunt]DE_Farkas')
local kg = player:getCharVar('[NMHunt]DE_Frostar')
local kh = player:getCharVar('[NMHunt]DE_Gaylia')
local ki = player:getCharVar('[NMHunt]DE_Golden Moon')
local kj = player:getCharVar('[NMHunt]DE_Haela')
local kk = player:getCharVar('[NMHunt]DE_Igninitis')
local kl = player:getCharVar('[NMHunt]DE_Ismzal')
local km = player:getCharVar('[NMHunt]DE_Jewel')
local kn = player:getCharVar('[NMHunt]DE_Kalseru')
local ko = player:getCharVar('[NMHunt]DE_Kuskyn')
local kp = player:getCharVar('[NMHunt]DE_Laimus')
local kq = player:getCharVar('[NMHunt]DE_Luna')
local kr = player:getCharVar('[NMHunt]DE_Malok')
local ks = player:getCharVar('[NMHunt]DE_Mireille')
local kt = player:getCharVar('[NMHunt]DE_Myrinn')
local ku = player:getCharVar('[NMHunt]DE_Neldor')
local kv = player:getCharVar('[NMHunt]DE_Nightwing')
local kw = player:getCharVar('[NMHunt]DE_Oddfinnur')
local kx = player:getCharVar('[NMHunt]DE_Orion')
local ky = player:getCharVar('[NMHunt]DE_Pindious')
local kz = player:getCharVar('[NMHunt]DE_Quintus')
local la = player:getCharVar('[NMHunt]DE_Remus')
local lb = player:getCharVar('[NMHunt]DE_Rotnam')
local lc = player:getCharVar('[NMHunt]DE_Saphil')
local ld = player:getCharVar('[NMHunt]DE_Sheedra')
local le = player:getCharVar('[NMHunt]DE_Skeltos')
local lf = player:getCharVar('[NMHunt]DE_Soril')
local lg = player:getCharVar('[NMHunt]DE_Sulfu')
local lh = player:getCharVar('[NMHunt]DE_Talila')
local li = player:getCharVar('[NMHunt]DE_Throar')
local lj = player:getCharVar('[NMHunt]DE_Turilla')
local lk = player:getCharVar('[NMHunt]DE_Usunaar')
local ll = player:getCharVar('[NMHunt]DE_Viktas')
local lm = player:getCharVar('[NMHunt]DE_Wilda')
local ln = player:getCharVar('[NMHunt]DE_Wynstar')

if amount == 1 then 

player:printToPlayer(string.format('-------------------------------------------------------------------------------------------'), xi.msg.channel.SYSTEM_3)

player:printToPlayer(string.format('NM Hunt Kill Count Tier 1--Current Kills are %s of 50--------------------------------------',player:getCharVar('[NMHunt]TOneKills')), xi.msg.channel.SYSTEM_3)

player:printToPlayer(string.format('-------------------------------------------------------------------------------------------'),  xi.msg.channel.SYSTEM_3)
player:printToPlayer(string.format('Ailmar %s | Amara %s | Aquarun %s | Axil %s | Bellas %s | ',aa,ab,ac,ad,ae), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Bonna %s | Brina %s | Celestia %s | Cluym %s | Daemeon %s | ',af,ag,ah,ai,aj), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Dark Rain %s | Diamond %s | Dracyian %s | Edmyla %s | Elora %s | ',ak,al,am,an,ao), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Estelar %s | Finrod %s | Fundar %s | Gelda %s | Golvig %s | ',ap,aq,ar,as,at), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Haemir %s | Igor %s | Ithi %s | Jhaan %s | Keara %s | ',au,av,aw,ax,ay), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Kyla %s | Lavatius %s | Lunarex %s | Malumka %s | Misi %s | ',az,ba,bb,bc,bd), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Mysris %s | Nemredilth %s | Nindr  %s | Olwyn %s | Orym  %s | ',be,bf,bg,bh,bi), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Pondra %s | Ragna %s | Rennyn %s | Sabir  %s | Sapphire %s | ',bj,bk,bl,bm,bn), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Shikta %s | Slyvek %s | Star Light %s | Sunshine %s | Tanulia %s | ',bo,bp,bq,br,bs), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Tisnip %s | Turvass %s | Vaegon  %s | Vinelle %s | Wilkass %s | ',bt,bu,bv,bw,bx), 3, xi.msg.channel.system_3)

elseif amount == 2 then 

player:printToPlayer(string.format('-------------------------------------------------------------------------------------------'), xi.msg.channel.SYSTEM_3)

player:printToPlayer(string.format('NM Hunt Kill Count Tier 2--Current Kills are %s of 50--------------------------------------',player:getCharVar('[NMHunt]TTwoKills')), xi.msg.channel.SYSTEM_3)

player:printToPlayer(string.format('-------------------------------------------------------------------------------------------'),  xi.msg.channel.SYSTEM_3)
player:printToPlayer(string.format('Akibrus %s | Amerstal %s | Asralyn %s | Ayldrad %s | Bellesta %s | ',by,bz,ca,cb,cc), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Bonnwynn %s | Brobek %s | Chalia %s | Coalak %s | Daernip %s | ',cd,ce,cf,cg,ch), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Darvyn %s | Digroi %s | Dray %s | Eiki %s | Elwin %s | ',ci,cj,ck,cl,cm), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Fabien %s | Flammedra %s | Gaemon %s | Gembelle %s | Gremin %s | ',cn,co,cp,cq,cr), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Hastos %s | Ilbryn %s | Jaderyn %s | Jinvia %s | Kezda %s | ',cs,ct,cu,cv,cw), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Kymil %s | Lavinia %s | Lymseia  %s | Merlara %s | Misma %s | ',cx,cy,cz,da,db), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Mystique %s | Nesterin  %s | Noi %s | Onas  %s | Pearl Moon %s | ',dc,dd,de,df,dg), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Pondral %s | Ragriel %s | Reyda %s | Saeya %s | Sarielle %s | ',dh,di,dj,dk,dl), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Shirmyl %s | Snowflake %s | Starburst %s | Sybella %s | Tazlen %s | ',dm,dn,lo,dp,dq), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Tisthel %s | Twilight %s | Vaella %s | Virfi %s | Wiska %s | ',dr,ds,dt,du,dv), 3, xi.msg.channel.system_3)

elseif amount == 3 then 

player:printToPlayer(string.format('-------------------------------------------------------------------------------------------'), xi.msg.channel.SYSTEM_3)

player:printToPlayer(string.format('NM Hunt Kill Count Tier 3--Current Kills are %s of 50--------------------------------------',player:getCharVar('[NMHunt]TThreeKills')), xi.msg.channel.SYSTEM_3)

player:printToPlayer(string.format('-------------------------------------------------------------------------------------------'),  xi.msg.channel.SYSTEM_3)
player:printToPlayer(string.format('Akkar %s | Angor %s | Astra %s | Azariah %s | Belstram %s | ',dw,dx,dy,dz,ea), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Bragi %s | Brulin %s | Chandrelle %s | Corym %s | Dagen %s | ',eb,ec,ed,ee,ef), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Delvin %s | Dimlinn %s | Drusila %s | Eilivur %s | Engar %s | ',eg,eh,ei,ej,ek), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Fada %s | Floki %s | Galdor %s | Glacitus %s | Gusak %s | ',el,em,en,eo,ep), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Heptin %s | Ilyrana %s | Jai-Blynn %s | Jodis %s | Killin %s | ',eq,er,es,et,eu), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Kyra %s | Lija %s | Lyra %s | Midnight %s | Mistmael %s | ',ev,ew,ex,ey,ez), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Nalra %s | Night Moon %s | Norok %s | Onnyx %s | Peregrine %s | ',fa,fb,fc,fd,fe), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Prodos %s | Rainbow %s | Rhenalyrr %s | Sakakara %s | Serpretus %s | ',ff,fg,fh,fi,fj), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Silver Star %s | Sola %s | Stardust %s | Syfas %s | Tendris %s | ',fk,fl,fm,fn,fo), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Tiznys %s | Twinkle %s | Vasha %s | Vixen %s | Wispmaral %s | ',fp,fq,fr,fs,ft), 3, xi.msg.channel.system_3)

end
end

return commandObj
